### ISSUE TITLE
上传直接报错

### ISSUE THREAD

**Issue by xclion** [lesonli/react-native-aliyun-oss#1]
let date = new Date();
                date = date.toGMTString();

                let upload_conf = {
                    bucketName:'huazhiyp-app',
                    sourceFile:response.uri,
                    ossFile:'images/xxx.jpg',
                    updateDate:date};

                 let uploadProgress = data => console.log(data);
                 AliyunOSS.addEventListener('uploadProgress',uploadProgress);

                AliyunOSS.uploadObjectAsync(upload_conf)
                    .then((resp) => {
                        console.log(resp);
                        AliyunOSS.removeEventListener('uploadProgress',uploadProgress);
                    })
                    .catch((err)=>{
                        console.log(err);
                    })

                this.setState({
                    avatarSource: source
                });

===============================================================
Error: not respond this method

    at createErrorFromErrorData (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7371:11)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7334:35
    at MessageQueue.__invokeCallback (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7714:10)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7566:8
    at guard (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7485:1)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7565:1)
    at onmessage (http://localhost:8081/debuggerWorker.js:44:56)

有详细的说明吗，一直上传不上去。

**Comment by lesonli** [comment]
从新更新一下吧，可能之前上传的代码正在做修改 @xclion

**Comment by iou90** [comment]
Please confirm your response.uri is valid and make it clear where the error was thrown (which line ?).

**Comment by xclion** [comment]
我就是装的最新的，之前按照教程上需要安装SDK，但是安装上Xcode会报错，发现调用重复，我把SDK删除就可以了正常编译了。

我更新了下，但是报错仍然一样。提示上面的错误信息。

**Comment by iou90** [comment]
https://github.com/huangzuizui/react-native-file-opener/issues/2 May help you. @xclion

**Comment by xclion** [comment]
@iou90 Thank you very much, really can not real machine debugging, error.

**Comment by xclion** [comment]
真机调试下，输出的日志是这样的，麻烦您看下哪里出问题了，好吗。
2016-11-23 10:39:55.297 [info][tid:com.facebook.react.AliyunOSSQueue][RCTAliyunOSS.m:41] OSSLog: 已开启
2016-11-23 10:39:55.297405 HzypProject[7531:2199043] OSSLog: 已开启
2016-11-23 10:39:55.312149 HzypProject[7531:2199043] uploadingFileURL: file:/var/mobile/Containers/Data/Application/CDBFF231-7F84-4B42-B4AF-4E9AB1A3984B/Documents/images/38259988-22DA-4629-8865-9FED2583D2CC.jpg -- file:///
2016-11-23 10:39:55.314643 HzypProject[7531:2199043] [Verbose]: send request --------
2016-11-23 10:39:55.315019 HzypProject[7531:2199041] [Verbose]: start to intercept request
2016-11-23 10:39:55.315213 HzypProject[7531:2199041] [Verbose]: signing intercepting -
2016-11-23 10:39:55.315426 HzypProject[7531:2199041] [Debug]: string to sign: PUT

image/jpeg
Wed, 23 Nov 2016 02:39:55 GMT
/huazhiyp-app/images/xxx.jpg
2016-11-23 10:39:55.315936 HzypProject[7531:2199041] objectKey: images/xxx.jpg
2016-11-23 10:39:55.316069 HzypProject[7531:2199041] upload object failed, error: Error Domain=com.aliyun.oss.clientError Code=3 "(null)" UserInfo={ErrorMessage=File doesn't exist}

**Comment by iou90** [comment]
@xclion I reproduced the issue just now when the sourceFile property is invalid.

YellowBox.js:69 Possible Unhandled Promise Rejection (id: 0):
not respond this method
Error: not respond this method
    at createErrorFromErrorData (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7303:11)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7266:35
    at MessageQueue.__invokeCallback (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7650:10)
    at http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7502:8
    at guard (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7421:1)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false:7501:1)
    at onmessage (http://localhost:8081/debuggerWorker.js:44:56)console.warn @ YellowBox.js:69onUnhandled @ Promise.js:25onUnhandled @ rejection-tracking.js:71(anonymous function) @ JSTimers.js:80callTimer @ JSTimersExecution.js:95callTimers @ JSTimersExecution.js:136__callFunction @ MessageQueue.js:236(anonymous function) @ MessageQueue.js:108guard @ MessageQueue.js:46callFunctionReturnFlushedQueue @ MessageQueue.js:107onmessage @ debuggerWorker.js:44
