### ISSUE TITLE
android 上传图片奔溃

### ISSUE THREAD

**Issue by vonyoki** [lesonli/react-native-aliyun-oss#10]
android 上传图片的时候奔溃

 E/unknown:ReactNative: Exception in native call
                                                                      java.lang.NullPointerException
                                                                          at com.alibaba.sdk.android.oss.common.utils.OSSUtils.populateRequestMetadata(OSSUtils.java:71)
                                                                          at com.alibaba.sdk.android.oss.internal.InternalReq
uestOperation.putObject(InternalRequestOperation.java:143)
                                                                          at com.alibaba.sdk.android.oss.OSSClient.asyncPutObject(OSSClient.java:152)
                                                                          at com.dskj.dscj.aliyunoss.aliyunossModule.uploadObjectAsync(aliyunossModule.java:128)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)

**Comment by fatfatson** [comment]
我的也是
![image](https://user-images.githubusercontent.com/5842874/35624165-267a70f8-06c9-11e8-9d2e-ce2baa49dfbf.png)

**Comment by fatfatson** [comment]
发现问题了，请叫我雷锋
首先，upload的config里必须有一个updateDate属性，因为这是java函数里的参数，首页示例代码上没有体现，可以自己去看node_module下面看代码。
然后，其实java里把那个参数设置到metadata里是不对的，必须注释掉，不然一直报授权验证失败的错误。

**Comment by wuhanchu** [comment]
const uploadConfig = {
    bucketName: "",
    sourceFile: sourceFile, // local file path
    ossFile: ossFile, // the file path uploaded to oss
    updateDate: "Tue, 01 Nov 2011 03:16:05 GMT"
  };

updateDate随便填个数据就可以了。
